name: JFrog Artifactory CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.0.0
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ENV_ACCESS_TOKEN }}

      - name: Run JFrog CLI
        run: |
          jf rt bce
          jf rt bag
          jf rt bp
